version: "3"
services:
  db:
    container_name: data-tag-manager_db
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_tag_manager
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --sql-mode="STRICT_TRANS_TABLES"
