// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Item struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Metas       []*Meta `json:"metas"`
	Tags        []*Tag  `json:"tags"`
}

type ItemTemplate struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	MetaKeys []*MetaKey `json:"metaKeys"`
}

type Meta struct {
	ID      string   `json:"id"`
	MetaKey *MetaKey `json:"metaKey"`
	Value   string   `json:"value"`
}

type MetaKey struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type MutationMeta struct {
	MetaKey *MutationMetaKey `json:"metaKey"`
	Value   string           `json:"value"`
}

type MutationMetaKey struct {
	ID   *string `json:"id"`
	Name string  `json:"name"`
}

type MutationTag struct {
	ID     *string      `json:"id"`
	Parent *MutationTag `json:"parent"`
	Level  int          `json:"level"`
	Name   string       `json:"name"`
}

type NewItem struct {
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Metas       []*MutationMeta `json:"metas"`
	Tags        []*MutationTag  `json:"tags"`
}

type Tag struct {
	ID     string `json:"id"`
	Parent *Tag   `json:"parent"`
	Level  int    `json:"level"`
	Name   string `json:"name"`
}
